# .sops.yaml
keys:
    - &desktop age1nn2vewqrej5sn9lqkh3sf0slgj7cemmlre03l286vx9cu59k9u9qsyttcd
creation_rules:
    - path_regex: secrets/secrets.yaml
      key_groups:
          - age:
                - *desktop
