source = hyprcolors.conf
source = animations/LimeFrenzy.conf
source = windowRules.conf
source = keybinds.conf
monitor = eDP-1, 2160x1440@60, auto, 1.0
exec-once = uwsm app -t service foot -- --server
exec-once = uwsm app -t service stash -- watch
exec-once = uwsm app nm-applet
exec-once = uwsm app ambxst
exec-once = uwsm app -t service hjem-impure
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
env = GTK_THEME,oomox-snazzy
general {
  gaps_in = 2
  gaps_out = 4
  border_size = 4
  col.active_border = rgba(243,139,168,1.0) rgba(243,139,168,1.0) rgba(219,232,151,1.0) rgba(178,231,173,1.0) rgba(120,169,255,1.0) rgba(255,171,145,1.0) 
  col.inactive_border = $tertiary
  resize_on_border = true
  allow_tearing = false
  layout = scrolling
}
# fix pixelation on HiDPI
xwayland {
  force_zero_scaling = true
}

group {
  col.border_active = $tertiary
  col.border_inactive = $tertiary_container
  drag_into_group = 2
  groupbar {
    font_family = CaskaydiaMono Nerd font
    font_size = 12
    height = 16
    text_color = $on_tertiary_container
    col.active = $tertiary
    col.inactive = $tertiary_container
    col.locked_active = $secondary
    col.locked_inactive = $secondary_container
  }
}

decoration {
  rounding = 8
  rounding_power = 1.0
  active_opacity = 1.0
  inactive_opacity = 1.0

  shadow {
    enabled = false
    range = 4
    render_power = 3
    color = $shadow
  }

  blur {
    enabled = true
    size = 4
    passes = 2
    vibrancy = 0.4
  }
}

dwindle {
  preserve_split = true # You probably want this
}

scrolling {
  fullscreen_on_one_column = false
  follow_focus = true
  focus_fit_method = 1
  direction = right
  follow_min_visible = 0.2
  explicit_column_widths = 0.5, 1.0
}
master {
  new_status = master
}

misc {
  force_default_wallpaper = 1 # Set to 0 or 1 to disable the anime mascot wallpapers
  disable_hyprland_logo = true # If true disables the random hyprland logo / anime girl background. :(
  vrr = true
  session_lock_xray = true
}

# Input
input {
  kb_layout = us
  kb_variant =
  kb_model =
  kb_rules =
  kb_options = caps:swapescape
  follow_mouse = 1
  sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
  touchpad {
    natural_scroll = true
    middle_button_emulation = false
  }
}

# guestures
gesture = 3, horizontal, workspace
gesture = 2, pinchin, dispatcher, exec, fuzzel

