{...}: {
  hj.rum.desktops.hyprland.settings = {
    "$mainMod" = "SUPER";
    "$scriptsDir" = "$HOME/.config/hypr/scripts";
    "$UserConfigs" = "$HOME/.config/hypr/UserConfigs";
    "$UserScripts" = "$HOME/.config/hypr/UserScripts/";
    "$files" = "thunar";
    "$term" = "wezterm-gui";
    "exec" = "hyprctl dispatch submap global";
    "submap" = "global";
    # bind = [
    #   "CTRL ALT , Delete , exec , hyprctl dispatch exit 0"
    #   "$mainMod , Q , killactive ,"
    #   "ALT , F , fullscreen ,"
    #   "$mainMod SHIFT , Q , exec , $scriptsDir/KillActiveProcess.sh"
    #   "$mainMod , Space , togglefloating ,"
    #   "$mainMod ALT , F , exec , hyprctl dispatch workspaceopt allfloat"
    #   "$mainMod , Backspace , exec , wlogout-new"
    #   "$mainMod SHIFT , M , exec , pkill rofi || $HOME/.config/rofi/applets/bin/mpd.sh"
    #   "$mainMod CTRL , D , layoutmsg , removemaster"
    #   "$mainMod , M , exec , hyprctl dispatch splitratio 0.3"
    #   "$mainMod , P , pseudo ,"
    #   "$mainMod CTRL , Return , layoutmsg , swapwithmaster"
    #   "$mainMod , G , togglegroup ,"
    #   "$mainMod CTRL , tab , changegroupactive ,"
    #   "ALT , tab , cyclenext ,"
    #   "ALT , tab , bringactivetotop ,"
    #   "$mainMod , code:10 , workspace , 1"
    #   "$mainMod , code:11 , workspace , 2"
    #   "$mainMod , code:12 , workspace , 3"
    #   "$mainMod , code:13 , workspace , 4"
    #   "$mainMod , code:14 , workspace , 5"
    #   "$mainMod , code:15 , workspace , 6"
    #   "$mainMod , code:16 , workspace , 7"
    #   "$mainMod , code:17 , workspace , 8"
    #   "$mainMod , code:18 , workspace , 9"
    #   "$mainMod , code:19 , workspace , 10"
    #   "$mainMod SHIFT , code:10 , movetoworkspace , 1"
    #   "$mainMod SHIFT , code:11 , movetoworkspace , 2"
    #   "$mainMod SHIFT , code:12 , movetoworkspace , 3"
    #   "$mainMod SHIFT , code:13 , movetoworkspace , 4"
    #   "$mainMod SHIFT , code:14 , movetoworkspace , 5"
    #   "$mainMod SHIFT , code:15 , movetoworkspace , 6"
    #   "$mainMod SHIFT , code:16 , movetoworkspace , 7"
    #   "$mainMod SHIFT , code:17 , movetoworkspace , 8"
    #   "$mainMod SHIFT , code:18 , movetoworkspace , 9"
    #   "$mainMod SHIFT , code:19 , movetoworkspace , 10"
    #   "$mainMod SHIFT , bracketleft , movetoworkspace , -1"
    #   "$mainMod SHIFT , bracketright , movetoworkspace , +1"
    #   "$mainMod CTRL , code:10 , movetoworkspacesilent , 1"
    #   "$mainMod CTRL , code:11 , movetoworkspacesilent , 2"
    #   "$mainMod CTRL , code:12 , movetoworkspacesilent , 3"
    #   "$mainMod CTRL , code:13 , movetoworkspacesilent , 4"
    #   "$mainMod CTRL , code:14 , movetoworkspacesilent , 5"
    #   "$mainMod CTRL , code:15 , movetoworkspacesilent , 6"
    #   "$mainMod CTRL , code:16 , movetoworkspacesilent , 7"
    #   "$mainMod CTRL , code:17 , movetoworkspacesilent , 8"
    #   "$mainMod CTRL , code:18 , movetoworkspacesilent , 9"
    #   "$mainMod CTRL , code:19 , movetoworkspacesilent , 10"
    #   "$mainMod , mouse_down , workspace , e+1"
    #   "$mainMod , mouse_up , workspace , e-1"
    #   ", xf86Display , exec , $scriptsDir/TouchPad.sh"
    #   ", code:179 , exec , $scriptsDir/TouchPad.sh"
    #   "$mainMod SHIFT , F6 , exec , $scriptsDir/ScreenShot.sh --area"
    #   "$mainMod CTRL , F6 , exec , $scriptsDir/ScreenShot.sh --in5"
    #   "$mainMod ALT , F6 , exec , $scriptsDir/ScreenShot.sh --in10"
    #   "ALT , F6 , exec , $scriptsDir/ScreenShot.sh --active"
    #   ", switch:Lid Switch , exec , hyprlock && sleep 10 && hyprctl dispatch dpms off"
    #   "$mainMod SHIFT , X , exec , ani-cli --rofi"
    #   "$mainMod , Return , exec , uwsm app $term"
    #   "$mainMod , T , exec , uwsm app $files"
    #   "$mainMod ALT , C , exec , $UserScripts/RofiCalc.sh"
    #   "$mainMod SHIFT , T , exec , pypr toggle yazi"
    #   "$mainMod SHIFT , Return , exec , pypr toggle term"
    #   "$mainMod SHIFT , D , exec , pypr toggle spotify"
    #   "$mainMod , Z , exec , pypr zoom"
    #   "$mainMod SHIFT , O , exec , $UserScripts/ZshChangeTheme.sh"
    #   "ALT_L SHIFT , , exec , $scriptsDir/SwitchKeyboardLayout.sh"
    #   "$mainMod SHIFT , a , movetoworkspace , special"
    #   "$mainMod ALT , P , submap , passthru"
    #   "$mainMod ALT , P , submap , reset"
    # ];
  };
}
